# source TFRecord directory
srcTfrecDir:

# destination TFRecord suffix name
destTfrecDir:

# normalization stats directory
normStats:
  scalar_params:
  centroid:
  diff_img:

nProcesses: 10  # number of processes in parallel

# auxiliary parameters needed for normalization of some features
auxParams:
  nr_transit_durations: 5
  # 2 * 2.5 + 1,  # 2 * 4 + 1,  # number of transit durations (2*n+1, n on each side of the transit)
  num_bins_loc: 31  # 31, 201
  num_bins_glob: 301  # 301, 2001
