
# path to output directory used to save results
output_dir: null
# process results either from TESS SPOC 2-min "2min" or FFI "ffi" data
data_collection_mode: null
# path to CSV file with TIC IDs to generate results for
tic_ids_fp: null
# number of processes to run application in parallel
num_processes: -1
# number of jobs to split the TIC IDs through
num_jobs: -1
# set to "true" or "false". If "true", it will create a CSV file with URLs to the SPOC DV reports for each TCE in the
# queried TICs
download_spoc_data_products: 'false'
# path to a directory containing the light curve FITS files and DV XML files for the TIC IDs and sector runs that you
# want to query; set to "null" otherwise
external_data_repository: null

### FIXED RUN PARAMETERS ###
# path to configuration file used to preprocess light curve data into a TFRecord dataset
lc_preprocessing_config_fp: exominer_pipeline/config_lc_preprocessing.yaml
# attributes to show for each example in the TFRecord dataset table
data_fields_tfrec_tbl:
  uid: str
  target_id: int
  tce_plnt_num: int
  sector_run: str
# path to configuration file used to preprocess difference image data
diff_img_preprocessing_config_fp: exominer_pipeline/config_diff_img_preprocessing.yaml
# path to configuration file used to add difference image data to TFRecord dataset
diff_img_add_tfrecord_dataset_config_fp: exominer_pipeline/config_add_diff_img_tfrecords.yaml
# path to configuration file used to normalize features in TFRecord dataset
normalize_tfrec_data_config_fp: exominer_pipeline/config_normalize_data.yaml
exominer_models:
  # exominer_phot-vetting: /models/exominer-plusplus_cv-iter0-model0_cv_tfrecords_tess-spoc-tces_2min-s1-s88_exominerpp_pr-auc-pc_3-6-2026_1558.keras
  phot-vetting: /models/phot_vetting/
  # phot-vetting: exominer_pipeline_data/models/phot_vetting
    # single: /models/phot_vetting/exominer-plusplus-sngle_cv-iter0-model0_tess-spoc-tces_2min-s1-s98_10-folds_added-ntps_20260615_212500.keras
    # cv_ensemble: /models/phot_vetting/exominer-plusplus-ensble_cv-iter0_tess-spoc-tces_2min-s1-s98_10-folds_added-ntps_20260615_212500.keras
    # full_cv_ensemble: /models/phot_vetting/exominer-plusplus-ensble-all_cv_tess-spoc-tces_2min-s1-s98_10-folds_added-ntps_20260615_212500.keras 
  planet-validation: /models/planet_validation/
  # planet-validation: exominer_pipeline_data/models/planet_validation
    # single: /models/planet-validation/exominer-plusplus-sngle_cv-iter0-model0_tess-spoc-tces_2min-s1-s98_10-folds-matched-distribution-2min-paper-by-weighted-loss_exominerpp_validation_no-secondaries_20260526_151727.keras
    # cv_ensemble: /models/planet-validation/exominer-plusplus-ensble_cv-iter0_tess-spoc-tces_2min-s1-s98_10-folds-matched-distribution-2min-paper-by-weighted-loss_exominerpp_validation_no-secondaries_20260526_151727.keras
    # full_cv_ensemble: /models/planet-validation/exominer-plusplus-ensble-all_cv_tess-spoc-tces_2min-s1-s98_10-folds-matched-distribution-2min-paper-by-weighted-loss_exominerpp_validation_no-secondaries_20260526_151727.keras
classes_descriptions:
  PC: planet candidate
  AFP: astrophysical false positive
  NTP: non-transiting phenomenon
  NOT_PC: not a planet candidate
label_map:
  phot-vetting: 
    PC: 1
    AFP: 2
    NTP: 0
  planet-validation: 
    PC: 1
    NOT_PC: 0
clf_thr:
  phot-vetting: 0
  planet-validation: 0.5
# path to ExoMiner TensorFlow Keras model used to generate predictions
model_fp: null
# path to configuration file used for running inference
predict_config_fp: exominer_pipeline/config_predict_model.yaml
predict_metadata_fp: exominer_pipeline/predictions_metadata.yaml
dv_reports_metadata_fp: exominer_pipeline/dv_reports_metadata.yaml
# plot inputs to ExoMiner model for each TCE in the run
plot_inputs_to_exominer_model: false
pipeline_metadata_fp: exominer_pipeline/pipeline_info.yaml
# number of tasks each worker completes before getting killed and memory is released
max_tasks_per_child: 5
# max retries per target when querying MAST/S3 for lc and dv xml data
max_retries: 3
# delay exponential base between retries 
delay: 5