# Used to run non-interactive cpu jobs
#PBS -S /bin/bash
#PBS -N plot_dataset_examples_05-04-2025_split_norm
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=4:mem=128g:ngpus=1:model=rom_ait
#PBS -q normal 
#PBS -o /nobackup/jochoa4/work_dir/data/logging/plot_dataset_examples_05-04-2025_split_norm.out
#PBS -e /nobackup/jochoa4/work_dir/data/logging/plot_dataset_examples_05-04-2025_split_norm.err
#PBS -W group_list=a1509

module use -a /swbuild/analytix/tools/modulefiles

module load miniconda3/v4

source activate /nobackup/jochoa4/.conda/envs/exoplnt_dl_tf2_13

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/

export PYTHONPATH=/nobackup/jochoa4/work_dir/exoplanet_dl

python3 /nobackupp27/jochoa4/work_dir/exoplanet_dl/transit_detection/norm_pipeline/plot_examples_from_dataset.py &> /nobackupp27/jochoa4/work_dir/data/logging/plot_dataset_examples_05-04-2025_split_norm.txt
