# Used to run interactive jobs
#PBS -S /bin/bash
#PBS -N test_build_dataset
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=4:mem=32gb:ngpus=1:model=sky_gpu
# PBS -l place=free:excl
#PBS -l place=scatter:shared
#PBS -q dsg_gpu@pbspl4
#PBS -o /nobackup/jochoa4/work_dir/data/logging/test/build_dataset_06-16-25.out
#PBS -e /nobackup/jochoa4/work_dir/data/logging/test/build_dataset_06-16-25.err
#PBS -W group_list=a1509
#PBS -m bea


module use -a /swbuild/analytix/tools/modulefiles

module load miniconda3/v4

source activate transit_detection_dl_tf2_13

export PYTHONPATH=/nobackupp27/jochoa4/work_dir/exoplanet_dl

python3 /nobackupp27/jochoa4/work_dir/exoplanet_dl/transit_detection/norm_pipeline/norm_tfrec_dataset_split.py  &> /nobackupp27/jochoa4/work_dir/data/logging/test/build_dataset_06-16-25.txt
