# Used to run interactive jobs
#PBS -S /bin/bash
#PBS -N data_analysis
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=4:mem=32gb:ngpus=1:model=sky_gpu
# PBS -l place=free:excl
#PBS -l place=scatter:shared
#PBS -q dsg_gpu@pbspl4
#PBS -o /nobackup/jochoa4/work_dir/data/logging/test/data_analysis.out
#PBS -e /nobackup/jochoa4/work_dir/data/logging/test/data_analysis.err
#PBS -W group_list=a1509
#PBS -m bea
