

 # CV destination data directory
dest_dir: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/cv_tfrecords_tess-spoc-2min_tces_s1-s98_stricter-phot-pcs_7-14-2026_1417/
# TFRecord source directory
src_tfrec_dir: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess-spoc-2min_tces_s1-s98_stricter-phot-pcs_7-14-2026_1417/
# table that maps a TCE to a given TFRecord file in the source TFRecords
src_tfrec_tbl_fp: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess-spoc-2min_tces_s1-s98_stricter-phot-pcs_7-14-2026_1417/shards_tbl.csv

n_processes: 36

# directory with the TCE tables for each fold in the labeled data set
labeled_shard_tbls_dir: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/cv_tfrecords_tess-spoc-2min_tces_s1-s98_stricter-phot-pcs_7-14-2026_1417/shard_tables/eval

# directory with the TCE tables for each fold for the unlabeled data set
unlabeled_shard_tbls_dir: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/cv_tfrecords_tess-spoc-2min_tces_s1-s98_stricter-phot-pcs_7-14-2026_1417/shard_tables/predict

# string feature used to filter examples in source TFRecord dataset into fold shards (e.g., 'uid')
filter_field: 'uid'  # 'uid_obs_type'

# # batch size for source TFRecord
# src_tfrec_batch_size: 128

# number of TFRecord shards per CV fold
n_shards_fold: 50

# pattern used to look up unlabeled dataset tables
unlabeled_fold_tbl_pattern: unlabeled_dataset_tbl_fold*.csv

# parameters needed when creating CV iterations YAML
datasets: ['train', 'val', 'test']
# choose among 'rotating_fold', 'fixed_fold', 'random_fold'
choose_val_method: 'rotating_fold'
random_seed: 21
