# Run CV predict experiment in parallel (multiple iterations at the same time) on a single GPU node with multiple GPUs
# and using a combination of GNU parallel and job array
#PBS -S /bin/bash
#PBS -N cv_predict_exoplanet
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=36:ngpus=4:mem=360g:model=sky_gpu
# place the chunk wherever it is possible for the requested resources; share resources with other people
#PBS -l place=scatter:excl
#PBS -q dsg_gpu@pbspl4
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_cv_predict_exoplnt_mgpus_singlenode.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_cv_predict_exoplnt_mgpus_singlenode.err
#PBS -W group_list=a1509
#PBS -m bea
#PBS -J 1-2

# script for running inference for a single CV iteration
RUN_SH_SCRIPT=/nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_cv/run_predict_cv_iter_modular.sh

# config yaml file used to run inference
CONFIG_FP=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_cv/config_cv_predict.yaml

# config yaml file used to preprocess data for model inference
CONFIG_PREPROCESS_FP=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_cv/create_cv_dataset/config_preprocess_cv_folds_predict_tfrecord_dataset.yaml

# output directory
OUTPUT_DIR=/nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/cv_tess-spoc-2min_s1-s67_9-26-2024_1623_predict_unks/
mkdir -p $OUTPUT_DIR

# root directory for model file paths
MODELS_CV_ROOT_DIR=/nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/cv_tess-spoc-2min_s1-s67_9-26-2024_1623/

# number of GPUs to be used by this job array
N_GPUS_TOTAL=4

# number of total jobs per job in job array
NUM_TOTAL_JOBS=$((1 * 4))
# NUM_TOTAL_JOBS=10
# number of jobs run simultaneously
NUM_JOBS_PARALLEL=4

# run with GNU parallel
# run CV sh script
seq 0 $((NUM_TOTAL_JOBS - 1)) | parallel -j $NUM_JOBS_PARALLEL "$RUN_SH_SCRIPT {} $PBS_ARRAY_INDEX $CONFIG_FP $OUTPUT_DIR $N_GPUS_TOTAL $MODELS_CV_ROOT_DIR" true $CONFIG_PREPROCESS_FP true

# testing multi-node setup...
# seq 0 $((NUM_TOTAL_JOBS - 1)) | parallel -j $NUM_JOBS_PARALLEL --sshloginfile $PBS_NODEFILE "$RUN_SH_SCRIPT {} 0 $CONFIG_FP $OUTPUT_DIR $N_GPUS_TOTAL $N_CV_ITERS $N_MODELS_PER_CV_ITER"
