# results directory for processed data
dest_dir:
# file path to difference image data NumPy file
diff_img_data_fp:
mission: tess  # either 'kepler' or 'tess'
num_sampled_imgs: 5  # number of sampled quarters/sector runs
final_size:  # final size for preprocessed images before resizing
  x: 11
  y: 11
# upscale factor for resized images; final image size is (upscale_f['x'] * final_size['x'], upscale_f['y'] * final_size['y'])
upscale_f:
  x: 5
  y: 5
# exclude neighbors that are outside the target mask
exclude_neighbor_objs_outside: true
n_processes: 1  # number of processes to run jobs in parallel
n_jobs: 1 # total number of jobs
plot_prob: 1  # probability to plot preprocessing results for each example