datasets: ["test"]

datasets_fps:
  test: 
    
# data_fields:
  uid: "string"
  target_id: "int_scalar"
  tce_plnt_num: "int_scalar"
  label: "string"
  tce_period: "float_scalar"
  tce_duration: "float_scalar"
  tce_time0bk: "float_scalar"
  ruwe: "float_scalar"
  tce_prad: "float_scalar"
  tce_max_mult_ev: "float_scalar"

label_field_name: label

label_map:
  PC: 1
  AFP: 0
  NTP: 0

features_set:
  
feature_map: null

#  feature_name: feature_name_model
#  global_centr_view_adjscl_std_noclip: global_centr_view_std_noclip
#  local_centr_view_adjscl_std_noclip: local_centr_view_std_noclip
#  tce_dikco_msky_adjscl_norm: tce_dikco_msky_norm
#  tce_dikco_msky_err_adjscl_shifted_norm: tce_dikco_msky_err_norm


feature_map: null

config:
  multi_class: false

inference:
  batch_size: 32

write_model_summary: true
plot_model: false
verbose_model: 1