# Conduct ephemeris matching run.
#PBS -S /bin/bash
#PBS -N ephem_matching_exoplnt
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=128:model=rom_ait
#PBS -q debug
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_exoplnt_dl_ephem_matching.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_exoplnt_dl_ephem_matching.err
#PBS -W group_list=a1509
#PBS -m bea

source "$HOME"/.bashrc

conda activate exoplnt_dl_tf2_13

export PYTHONPATH=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

# create output directory for preprocessing results
OUTPUT_DIR=/Users/msaragoc/Projects/exoplanet_transit_classification/experiments/ephemeris_matching/tces_spoc_dv_2mindata_s1-s68_01-23-2024_1225
mkdir -p $OUTPUT_DIR
# script file path
SCRIPT_FP=/Users/msaragoc/Library/CloudStorage/OneDrive-NASA/Projects/exoplanet_transit_classification/codebase/data_wrangling/ephemeris_matching/run_ephemeris_match_multiproc.py
# config file path
CONFIG_FP=/Users/msaragoc/Library/CloudStorage/OneDrive-NASA/Projects/exoplanet_transit_classification/codebase/data_wrangling/ephemeris_matching/config_ephem_matching.yaml
# log file
LOG_FP=$OUTPUT_DIR/ephem_matching.log
touch $LOG_FP

python $SCRIPT_FP --config_fp=$CONFIG_FP &>> "$LOG_FP"
