# Used to run interactive jobs
#PBS -S /bin/bash
#PBS -N interactive_job
#PBS -l walltime=72:00:00
# DSG GPU v100 nodes
#PBS -l select=1:ncpus=9:mem=90g:ngpus=1:model=sky_gpu
#PBS -l place=free:shared
#PBS -q dsg_gpu@pbspl4
# Cabeus (A100, V100, ..., GPU nodes)
# PBS -l select=1:ncpus=15:mem=128g:ngpus=1:model=mil_a100
# PBS -l place=scatter:shared
# PBS -q gpu_devel@pbspl4
# non-GPU nodes
# PBS -l select=1:ncpus=40:model=cas_ait
# PBS -l select=1:ncpus=128:model=rom_ait
# PBS -q long
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/interactive_job.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/interactive_job.err
#PBS -W group_list=a1509
# PBS -W group_list=s2857
#PBS -m bea

# initialize conda and activate conda environment
# module use -a /swbuild/analytix/tools/modulefiles
# non-GH conda
# module load miniconda3/v4
# source activate exoplnt_dl_tf2_13
# GH conda (aarch64)
# module load miniconda3/gh2
# source activate exoplnt_dl_gh

# set path to codebase root directory
# export PYTHONPATH=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/search_neighbors/map_location_neighbors_to_pixel_frame.py
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/extracting/extract_data_from_tess_dv_xml.py
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/preprocessing/wrapper_preprocess_diff_img.py
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/preprocessing/preprocess_diff_img.py --config_fp=/nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/preprocessing/config_preprocessing.yaml
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/preprocessing/add_data_to_tfrecords.py
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/utils_manipulate_tfrecords.py
# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/tess_spoc_ffi/create_tfrecord_dataset_hpo.py