# Used to run interactive jobs
#PBS -S /bin/bash
#PBS -N data_analysis
#PBS -l walltime=02:00:00
# DSG GPU v100 nodes
# PBS -l select=1:ncpus=36:mem=360g:ngpus=1:model=sky_gpu
# PBS -l place=free:excl
# PBS -q dsg_gpu@pbspl4
# Cabeus (A100, V100, ..., GPU nodes)
# PBS -l select=1:ncpus=16:mem=128g:ngpus=1:model=mil_a100
# PBS -l place=scatter:shared
# PBS -q gpu_devel@pbspl4
# non-GPU nodes
#PBS -l select=1:ncpus=40:model=cas_ait
# PBS -l select=1:ncpus=1:model=rom_ait
#PBS -q debug
# Early Access Grace Hopper nodes
#PBS -lselect=1:ncpus=16:model=gra_h100:mem=400g
#PBS -q alpha_test
#PBS -A ARMD
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_data_analysis.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_data_analysis.err
# PBS -W group_list=a1509
#PBS -W group_list=s2857
#PBS -m bea

# initialize conda and activate conda environment
module use -a /swbuild/analytix/tools/modulefiles
# non-GH conda
module load miniconda3/v4
source activate exoplnt_dl_tf2_13
# GH conda (aarch64)
# module load miniconda3/gh2
# source activate exoplnt_dl_gh

# set path to codebase root directory
export PYTHONPATH=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

# python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/search_neighbors/map_location_neighbors_to_pixel_frame.py
python /nobackupp19/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src_preprocessing/diff_img/extracting/extract_data_from_tess_dv_xml.py