# Run inference for a single ensemble (single GPU); Configuration filepath is received as environment variable to the
# PBS script; Allows for running multiple configurations sequentially.
#PBS -S /bin/bash
#PBS -N shap_exoplnt_pred
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=9:model=sky_gpu:ngpus=1:mem=90gb
#PBS -l place=vscatter:shared
# #PBS -l select=1:ncpus=36:mpiprocs=4:model=sky_gpu
# #PBS -l select=10:ncpus=16:mpiprocs=1:model=san_gpu
#PBS -q dsg_gpu@pbspl4
# #PBS -q v100
# #PBS -q k40
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_shap_exoplnt_pred.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_shap_exoplnt_pred.err
#PBS -W group_list=a1509
#PBS -m bea
# #PBS -J 0-9
# #PBS -J 0-2

module list

source activate exoplnt_dl
# source activate /home6/msaragoc/work_dir/tools/python_envs/exoplnt_dl

cd /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

CONFIG_FILE_DIR=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/shap/shap_1-11-2022/runs_configs/
PREDICT_ENSEMBLE_SCRIPT=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/src/predict_ensemble_keras.py
PYOUT_DIR=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/shap/shap_1-11-2022/log_py/

echo Evaluating ensemble "$SHAP_CONFIG_RUN"; python "$PREDICT_ENSEMBLE_SCRIPT" --config_file="$CONFIG_FILE_DIR$SHAP_CONFIG_RUN"_predict.yaml &> "$PYOUT_DIR$SHAP_CONFIG_RUN"_predict_log_py.txt;
