# Check which KICs do not have FITS files and download them; using seq and parallel to parallelize the job.
#PBS -S /bin/bash
#PBS -N dwnld_missing_fits_files
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=12:model=san
#PBS -q long
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_missing_fits_files.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_missing_fits_files.err
#PBS -W group_list=a1509
#PBS -m bea

# source activate /home6/msaragoc/work_dir/tools/python_envs/py365_tfcpu

# cd /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/missing_fitsfiles_scripts/

seq 12 | parallel -j 12 -u --sshloginfile $PBS_NODEFILE "bash /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/missing_fitsfiles_scripts/get_missing_kepler_pfe{}.sh" 
