# Compute margin contributions for SHAP (multi-node); Uses job arrays; Number of processes is
# n_jobs_in_array*n_procs_python_pool
#PBS -S /bin/bash
#PBS -N shap_mc
#PBS -l walltime=08:00:00
# #PBS -l select=20:ncpus=10:mpiprocs=20:model=san
#PBS -l select=1:ncpus=15:model=san
#PBS -q long
#PBS -oe /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_shap_mc.out
# #PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_shap_mc.err
#PBS -W group_list=a1509
#PBS -m bea
#PBS -J 0-7

module list

source activate exoplnt_dl

cd /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

OUTPUT_FILE=/home6/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/shap/mc_$PBS_ARRAY_INDEX.txt

mpiexec python shap/compute_mcs.py --job_idx=$PBS_ARRAY_INDEX &> $OUTPUT_FILE

