# Conduct label noise injection experiments (multi-GPU multi-node); Using MPIEXEC and job arrays; One run (noise level)
# per process/GPU. Number of noise levels needs to be less or equal to mpiprocs*n_jobs_array.
#PBS -S /bin/bash
#PBS -N label_noise_injection_experiment_exoplnt
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=36:mpiprocs=4:model=sky_gpu:ngpus=4:mem=360g
#PBS -l place=scatter:exclhost
# #PBS -l select=1:ncpus=36:mpiprocs=4:model=sky_gpu
# #PBS -l select=10:ncpus=16:mpiprocs=1:model=san_gpu
#PBS -q dsg_gpu@pbspl4
# #PBS -q v100
# #PBS -q k40
#PBS -o /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_train_exoplnt_mgpus.out
#PBS -e /home6/msaragoc/jobs/Kepler-TESS_exoplanet/job_train_exoplnt_mgpus.err
#PBS -W group_list=a1509
#PBS -m bea
# #PBS -J 0-9
#PBS -J 0-2

module list

source activate exoplnt_dl

cd /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/codebase/

mpiexec python label_noise/inject_label_noise_experiment.py --job_idx=$PBS_ARRAY_INDEX &> /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/label_noise/job_$PBS_ARRAY_INDEX.txt
