commit_id: 52a6d216389a6f2606173c2ad060242738e623fe
model_architecture: ExoMinerJointLocalFlux
feature_map: null

features_set: # each key-value pair is feature_name: {'dim': feature_dim, 'dtype': feature_dtype}

  # unfolded flux
  unfolded_local_flux_view_fluxnorm: { 'dim': [ 20, 31 ], 'dtype': float }
  unfolded_local_flux_view_fluxnorm_var: { 'dim': [ 20, 31 ], 'dtype': float }
  tce_num_transits_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_num_transits_obs_norm: { 'dim': [ 1, ], 'dtype': float }

  # flux
  global_flux_view_fluxnorm: { 'dim': [ 301, 1 ], 'dtype': float }
  global_flux_view_fluxnorm_var: { 'dim': [ 301, 1 ], 'dtype': float }
  flux_global_stat_abs_min_norm: { 'dim': [ 1, ], 'dtype': float }

  local_flux_view_fluxnorm: { 'dim': [ 31, 1 ], 'dtype': float }
  local_flux_view_fluxnorm_var: { 'dim': [ 31, 1 ], 'dtype': float }
  flux_local_stat_abs_min: { 'dim': [ 1, ], 'dtype': float }

  # odd-even flux related features
  local_flux_odd_view_fluxnorm: { 'dim': [ 31, 1 ], 'dtype': float }
  local_flux_even_view_fluxnorm: { 'dim': [ 31, 1 ], 'dtype': float }
  local_flux_odd_view_fluxnorm_var: { 'dim': [ 31, 1 ], 'dtype': float }
  local_flux_even_view_fluxnorm_var: { 'dim': [ 31, 1 ], 'dtype': float }
  flux_even_local_stat_abs_min_norm: {'dim': [1,], 'dtype': float}
  flux_odd_local_stat_abs_min_norm: {'dim': [1,], 'dtype': float}

  # centroid related features
  local_centr_view_std_noclip: { 'dim': [ 31, 1 ], 'dtype': float }
  local_centr_view_std_noclip_var: { 'dim': [ 31, 1 ], 'dtype': float }

  # secondary related features
  local_weak_secondary_view_selfnorm: { 'dim': [ 31, 1 ], 'dtype': float }
  local_weak_secondary_view_selfnorm_var: { 'dim': [ 31, 1 ], 'dtype': float }
  tce_maxmes_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_albedo_stat_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_ptemp_stat_norm: { 'dim': [ 1, ], 'dtype': float }
  flux_weak_secondary_local_stat_abs_min_norm: { 'dim': [ 1, ], 'dtype': float }

  # other diagnostic parameters
  tce_max_mult_ev_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_max_sngle_ev_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_robstat_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_model_chisq_norm: { 'dim': [ 1, ], 'dtype': float }

  # bootstrap fa prob
  boot_fap_norm: { 'dim': [ 1, ], 'dtype': float }

  # ghost
  tce_cap_stat_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_hap_stat_norm: { 'dim': [ 1, ], 'dtype': float }

  # stellar parameters
  tce_sdens_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_steff_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_smet_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_slogg_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_smass_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_sradius_norm: { 'dim': [ 1, ], 'dtype': float }
  ruwe_norm: { 'dim': [ 1, ], 'dtype': float }
  mag_shift_norm: { 'dim': [ 1, ], 'dtype': float }

  # tce parameters
  tce_prad_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_period_norm: { 'dim': [ 1, ], 'dtype': float }

  # difference image
  # diff_imgs_std_trainset: { 'dim': [ 55, 55, 5 ], 'dtype': float }
  # oot_imgs_std_trainset: { 'dim': [ 55, 55, 5 ], 'dtype': float }
  # target_imgs: { 'dim': [ 55, 55, 5 ], 'dtype': float }
  diff_imgs_tc_std_trainset: { 'dim': [ 5, 55, 55 ], 'dtype': float }
  oot_imgs_tc_std_trainset: { 'dim': [ 5, 55, 55 ], 'dtype': float }
  snr_imgs_tc_std_trainset: { 'dim': [ 5, 55, 55 ], 'dtype': float }
  neighbors_imgs_tc_fixed_min_max_norm: { 'dim': [ 5, 55, 55 ], 'dtype': float }

  # quality: { 'dim': [ 5, 1], 'dtype': float }
  quality: { 'dim': [ 5, ], 'dtype': float }
  tce_dikco_msky_norm: { 'dim': [ 1, ], 'dtype': float }
  tce_dikco_msky_err_norm: { 'dim': [ 1, ], 'dtype': float }

#  # momentum dump
#  local_momentum_dump_view: { 'dim': [ 31, 1 ], 'dtype': float }
#  local_momentum_dump_view_var: { 'dim': [ 31, 1 ], 'dtype': float }

  # flux trend
  flux_trend_global_norm: { 'dim': [ 301, 1 ], 'dtype': float }
  flux_trend_global_norm_var: { 'dim': [ 301, 1 ], 'dtype': float }
  flux_trend_global_stat_min_norm: { 'dim': [ 1, ], 'dtype': float }
  flux_trend_global_stat_max_norm: { 'dim': [ 1, ], 'dtype': float }

  # flux periodogram
  pgram_smooth_norm: { 'dim': [ 674, 1 ], 'dtype': float }
  pgram_tpm_smooth_norm: { 'dim': [ 674, 1 ], 'dtype': float }
  pgram_smooth_max_power_norm: { 'dim': [ 1, ], 'dtype': float }
  pgram_tpm_smooth_max_power_norm: { 'dim': [ 1, ], 'dtype': float }

config:
  conv_branches:
    local_unfolded_flux:
      views:
      - unfolded_local_flux_view_fluxnorm
      - unfolded_local_flux_view_fluxnorm_var
      scalars:
      - tce_num_transits_obs_norm
      - tce_num_transits_norm
    global_flux:
      views:
      - global_flux_view_fluxnorm
      - global_flux_view_fluxnorm_var
      scalars:
      - flux_global_stat_abs_min_norm
    local_flux:
      views:
      - local_flux_view_fluxnorm
      - local_flux_view_fluxnorm_var
      scalars:
      - flux_local_stat_abs_min
    local_weak_secondary:
      views:
      - local_weak_secondary_view_selfnorm
      - local_weak_secondary_view_selfnorm_var
      scalars:
      - tce_ptemp_stat_norm
      - tce_albedo_stat_norm
      - tce_maxmes_norm
      - flux_weak_secondary_local_stat_abs_min_norm
    local_centroid:
      views:
      - local_centr_view_std_noclip
      - local_centr_view_std_noclip_var
      scalars:
      - mag_shift_norm
    local_odd_even:
      views:
      - local_flux_odd_view_fluxnorm
      - local_flux_odd_view_fluxnorm_var
      - local_flux_even_view_fluxnorm
      - local_flux_even_view_fluxnorm_var
      scalars:
      - flux_odd_local_stat_abs_min_norm
      - flux_even_local_stat_abs_min_norm
    flux_trend:
      views:
      - flux_trend_global_norm
      - flux_trend_global_norm_var
      scalars:
      - flux_trend_global_stat_max_norm
      - flux_trend_global_stat_min_norm
    flux_periodogram:
      views:
      - pgram_smooth_norm
      - pgram_tpm_smooth_norm
      scalars:
      - pgram_smooth_max_power_norm
      - pgram_tpm_smooth_max_power_norm
  scalar_branches:
    stellar:
    - tce_sdens_norm
    - tce_steff_norm
    - tce_smet_norm
    - tce_slogg_norm
    - tce_smass_norm
    - tce_sradius_norm
    - ruwe_norm
    dv_tce_fit:
    - boot_fap_norm
    - tce_cap_stat_norm
    - tce_hap_stat_norm
    - tce_period_norm
    - tce_max_mult_ev_norm
    - tce_max_sngle_ev_norm
    - tce_robstat_norm
    - tce_model_chisq_norm
    - tce_prad_norm
  diff_img_branch:
    imgs:
    - diff_imgs_tc_std_trainset
    - oot_imgs_tc_std_trainset
    - snr_imgs_tc_std_trainset
    - neighbors_imgs_tc_fixed_min_max_norm
    imgs_scalars:
    - quality
    scalars:
    - mag_shift_norm
    - tce_dikco_msky_norm
    - tce_dikco_msky_err_norm
  
  # optimization hyperparameters -------
  sgd_momentum: 0
  force_softmax: false
  multi_class: false
  loss: crossentropy
  focal_loss_gamma: 2.0
  focal_loss_alpha: 0.96
  focal_class_balancing: false
  lr: 4.176171931455995e-05  # 3.34e-04  # 4.176171931455995e-05
  optimizer: Adam  # AdamW
  
  # applied to dense layers in classification head and in scalar branches
  decay_rate: null  
  non_lin_fn: prelu
  weight_initializer: null
  
  # difference image hyperparameters ---------
  diff_img_conv_scalar_num_filters: 3
  diff_img_init_power_num_conv_filters: 2
  diff_img_kernel_size: 3
  diff_img_kernel_stride: 1
  diff_img_num_conv_blocks: 3
  diff_img_num_conv_ls_per_block: 3
  # diff_img_pool_size: 2
  # diff_img_pool_stride: 1
  
  # periodogram branch hyperparameters -----
  flux_periodogram_init_power_num_conv_filters: 3
  flux_periodogram_kernel_size: 5
  flux_periodogram_kernel_stride: 1
  flux_periodogram_num_conv_blocks: 2
  flux_periodogram_num_conv_ls_per_block: 3
  flux_periodogram_pool_size: 8
  flux_periodogram_pool_stride: 1
  
  # global (flux and trend) branch hyperparameters ----
  global_flux_init_power_num_conv_filters: 3
  global_flux_kernel_size: 5
  global_flux_kernel_stride: 1
  global_flux_num_conv_blocks: 2
  global_flux_num_conv_ls_per_block: 3
  global_flux_pool_size: 8
  global_flux_pool_stride: 1
  
  # local branch (flux and centroid) hyperparameters ------
  local_fluxes_init_power_num_conv_filters: 3
  local_fluxes_kernel_size: 6
  local_fluxes_kernel_stride: 1
  local_fluxes_num_conv_blocks: 2
  local_fluxes_num_conv_ls_per_block: 3
  local_unfolded_flux_num_filters_stats: 4
  local_fluxes_pool_size: 4
  local_fluxes_pool_stride: 1

  # shared conv hyperparameters ----
  use_attention_after_conv_layers: false
  use_skip_connection_conv_block: false
  batch_norm_after_conv_layers: false  
  # branch_dropout_rate_fc: 0.1211390996398814
  branch_num_fc_units: 3
  
  # attention for classification head hyperparameters ------
  use_attention_before_classification_head: false
  use_attention_scores: false
  attention_before_classification_head_max_key_dim: 3

  # classification head hyperparameters ------
  clf_head_fc_dropout_rate: 0.021491238286347598  # 0.2  # 0.021491238286347598
  clf_head_fc_neurons: 512
  clf_head_num_fc_layers: 4
  clf_head_fc_decay_rate: null

